default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: todo_tracker_development

test:
  <<: *default
  database: todo_tracker_test

production:
  <<: *default
  database: todo_tracker_production
  username: todo_tracker
  password: <%= ENV['TODO_TRACKER_DATABASE_PASSWORD'] %>
