default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:development :database) %>
  username: <%= Rails.application.credentials.dig(:development :username) %>
  password: <%= Rails.application.credentials.dig(:development :password) %>
  host: <%= Rails.application.credentials.dig(:development :host) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:test :database) %>
  username: <%= Rails.application.credentials.dig(:test :username) %>
  password: <%= Rails.application.credentials.dig(:test :password) %>
  host: <%= Rails.application.credentials.dig(:test :host) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production :database) %>
  username: <%= Rails.application.credentials.dig(:production :username) %>
  password: <%= Rails.application.credentials.dig(:production :password) %>
  host: <%= Rails.application.credentials.dig(:production :host) %>
